version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.4.0
    ports:
      - '4566-4599:4566-4599'
      - '8080:8080'
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EDGE_PORT=4566
      - DISABLE_CORS_CHECKS=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"